apiVersion: wasme.io/v1
kind: FilterDeployment
metadata:
  name: random-fail-filter
  namespace: default
spec:
  deployment:
    istio:
      kind: Deployment
  filter:
    config: "test"
    image: webassemblyhub.io/oleksiyp/random-fail-filter:TS
